scraper_site/scraperUI/urls.py
from django.urls import path

from . import views

app_name = 'scraperUI'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:search_term_id>/', views.details, name='details'),
    path('<int:search_term_id>/results/', views.results, name='results'),
    path('<int:search_term_id>/add/', views.add, name='add'),
]

scraper_site/scraper_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('scraperUI/', include('scraperUI.urls')),
    path('admin/', admin.site.urls),
]

scraper_site/scraperUI/models.py
import datetime

from django.db import models
from django.utils import timezone


class RedditSearchTerm(models.Model):
    searched_term = models.CharField(max_length=200)
    date_searched = models.DateTimeField('Date Searched')

    def __str__(self):
        return f'"{self.searched_term}" searched on {self.date_searched}'

    def was_searched_recently(self):
        return self.date_searched >= timezone.now() - datetime.timedelta(days=1)


class RedditSearchResult(models.Model):
    search_term = models.ForeignKey(RedditSearchTerm, on_delete=models.CASCADE)
    post_title = models.CharField(max_length=200)
    author = models.CharField(max_length=30)
    subreddit = models.CharField(max_length=30)
    upvotes = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    # todo add rewards field

    def __str__(self):
        return f'"{self.post_title}" by {self.author} on {self.subreddit}'

scraper_site/scraperUI/views.py
from django.shortcuts import get_object_or_404, render

from .models import RedditSearchResult, RedditSearchTerm

# todo not all views are complete yet, I still need to add more documentations as well as finish results and add (might remove results in the end)

def index(request):
    most_recent_search_terms = RedditSearchTerm.objects.order_by('-date_searched').distinct()[:3]
    most_recent_searches = {}
    for search_term in most_recent_search_terms:
        most_recent_searches[search_term] = RedditSearchResult.objects.filter(search_term=search_term).order_by('-upvotes').distinct()[:4]
    return render(request, 'scraperUI/index.html', {'search_results': most_recent_searches})


def details(request, search_term_id):
    search_term = get_object_or_404(RedditSearchTerm, pk=search_term_id)
    top_results = RedditSearchResult.objects.filter(search_term=search_term_id).order_by('-upvotes')
    return render(request, 'scraperUI/details.html', {'search_term': search_term, 'top_results': top_results})

def results(request, search_term_id):
    return HttpResponse(f"You're looking at the search results for search term {search_term_id}")

def add(request, search_term_id):
    return HttpResponse(f"You are searching for {search_term_id} on reddit")

scraper_site/scraperUI/templates/scraperUI/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details for {{search_term.searched_term}}</title>
    <link rel="stylesheet" href="{% static 'page_styles.css' %}">
</head>
<body>
    <h1>All results for {{search_term.searched_term}}</h1>
    <ul>
        {% for result in top_results %}
            <li>{{ result.post_title }}</li>
        {% endfor %}
    </ul>
</body>
</html>

scraper_site/scraperUI/templates/scraperUI/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="{% static 'page_styles.css' %}">
</head>
<body>
    <h1>Top Scraped Reddit Posts</h1>
    {% if search_results %}
        <ul>
        {% for search_term, results in search_results.items %}
            <h3>Top results for {{ search_term }}:</h3>
            {% for search_result in results %}
                <li><a href="{% url 'scraperUI:details' search_result.search_term.id %}">{{ search_result.post_title }}</a></li>
            {% endfor %}
        {% endfor %}
        </ul>
    {% else %}
        <p>No searches are available.</p>
    {% endif %}
</body>
</html>